import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/utils/Navbar'
import Sidebar from '@/components/utils/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test Article App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Navbar />
        <Sidebar />
        {children}
      </body>
    </html>
  )
}
